services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: GestioLAN-DB_TEST
    ports:
    # Per ora esponiamo la porta del database, ma in produzione non sarà così
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      # Per permettere connessioni da qualsiasi host, ma in produzione dovremo limitare questo
      - MARIADB_USER_HOST=%
    volumes:
      - type: bind
        source: ${RESOURCE_DEST_PATH}/test_builds/gestiolan-mysql
        target: /var/lib/mysql
        # bind:
          # create_host_path: false
    networks: 
      - gestionale_network # Nome del network per api e db
    healthcheck: # Per verificare che il database sia pronto prima di avviare l'API
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./src/GestioLan.API
      dockerfile: Dockerfile
    container_name: GestioLan.API_TEST
    ports:
      - "5169:8080"
    environment:
      - JWT-Settings__key=${JWT-Key}
      - ConnectionStrings__GestioLANConnection=Server=database;Port=3306;Database=${DB_NAME};User Id=${DB_USERNAME};Password=${DB_PASSWORD};SslMode=none;
      - ASPNETCORE_ENVIRONMENT=Development # Per ora teniamo Development per vedere gli errori
    volumes:
      - type: bind
        source: ${RESOURCE_DEST_PATH}/test_builds/uploads/users
        target: /app/data/uploads/users
        # bind:
          # create_host_path: false
      - type: bind
        source: ${RESOURCE_DEST_PATH}/test_builds/uploads/items
        target: /app/data/uploads/items
        # bind:
          # create_host_path: false
      - type: bind
        source: ${RESOURCE_DEST_PATH}/test_builds/logs
        target: /app/logs
        # bind:
          # create_host_path: false
    networks: 
      - gestionale_network # Nome del network per api e db
    depends_on: # Per assicurarsi che il database sia avviato prima dell'API
      database:
        condition: service_healthy

networks: 
  gestionale_network: 
    # external: true 
