services:
  api:
    build:
      context: .
      dockerfile: src/csharpAPI/Dockerfile
    container_name: GestioLAN-API
    ports:
      - "5169:8080"
    environment:
      - JWT-Settings__key=${JWT-Key}
      - ConnectionStrings__GestioLANConnection=Server=mariadb11;Port=3306;Database=${DB_NAME};User Id=${DB_USERNAME};Password=${DB_PASSWORD};SslMode=none;
      - ASPNETCORE_ENVIRONMENT=Development # Per ora teniamo Development per vedere gli errori
    networks: 
      - gestionale_network # Nome del network per api e db

networks: 
  gestionale_network: 
    external: true 
