services:
  api:
    build:
      context: .
      dockerfile: src/csharpAPI/Dockerfile
    container_name: GestioLAN-API
    ports:
      - "5169:8080"
    environment:
      # Nota: Server=db usa il nome del servizio definito sopra
      - ConnectionStrings__DefaultConnection=Server=mariadb11;Database=${DB_NAME};User Id=s${DB_USERNAME};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development # Per ora teniamo Development per vedere gli errori
    networks: 
      - gestionale_network # Nome del network per api e db

networks: 
  gestionale_network: 
    external: true 
