-- MySQL Script generated by MySQL Workbench
-- ven 24 ott 2025, 16:17:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gestionale_Casa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gestionale_Casa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gestionale_Casa` ;
USE `Gestionale_Casa` ;

-- -----------------------------------------------------
-- Table `Gestionale_Casa`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestionale_Casa`.`Categorie` (
  `id_categoria` INT NOT NULL,
  `nome_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nome_categoria_UNIQUE` (`nome_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestionale_Casa`.`Oggetti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestionale_Casa`.`Oggetti` (
  `id_oggetto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descrizione` VARCHAR(255) NULL,
  `quantita` INT NOT NULL,
  `percorso_immagine` VARCHAR(255) NULL,
  `id_categoria` INT NULL,
  PRIMARY KEY (`id_oggetto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
