# FASE 1: Build e Publish
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia il file di progetto per fare il restore delle librerie
COPY ["src/GestioLan.API/GestioLan.API.csproj", "src/GestioLan.API/"]
RUN dotnet restore "src/GestioLan.API/GestioLan.API.csproj"

# Copia tutto il codice e pubblica la release
COPY . .
WORKDIR "/src/src/GestioLan.API"
RUN dotnet publish "GestioLan.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# FASE 2: Runtime finale (Immagine leggera)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
# Copia solo la release dalla fase precedente
COPY --from=build /app/publish .

# Espone la porta interna del container
EXPOSE 8080

ENTRYPOINT ["dotnet", "GestioLan.API.dll"]